### ISSUE TITLE
move import outside of try/catch

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#527]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1469198/59546994-f6edc500-8f3f-11e9-8074-32507de3fda9.png)

@AndrewSerra 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AndrewSerra** [comment]
Sorry I wasn't quite sure what to do. Should I just add an explanation of what is different when the import is inside or outside and how the behavior changes? or should I just change them?

**Comment by AndrewSerra** [comment]
**Description of the bug**
The problem with the warning we get in the picture [here](https://github.com/GroceriStar/sd/issues/527#issue-456498686) is about repetitive code in tests.js files, all files under examples/ directory. This is because the only difference in these files are the import path name and the description of the tests.

**To Reproduce**

1. Go to pull request [#517](https://codeclimate.com/github/GroceriStar/sd/pull/517) to see the message.
2. As you scroll down you will see different places where similar blocks of code are present. They are all under sd/tests/ directory

**Expected Behavior**
Currently, everything works. The expected result is to not get a refactoring warning during pull requests.

**Screenshots**
No screenshots are applicable.

**Additional Context**
An improvement suggestion: 
```
describe('tests for allergy', () => {
  it('allergies data files returns array', () => {
    expect(staticData.allergies).not.toBe('')
  })
})
``` 
instead of having a bunch of "describe" and "it" blocks for tests, we can have a "describe" that contains all the "it" blocks similar to sd/tests/testFilesCheck/exampleFiles.test.js

**Comment by AndrewSerra** [comment]
@atherdon about the try/catch block import, should I just pull them outside now? Because as far as I know the codeclimate issue is something else

**Comment by atherdon** [comment]
thanks for the clear explanation. it save me a lot of time.

at this point i want just to not have an import of our examples and schemas inside of try/catch

**Comment by atherdon** [comment]
but your suggestion is right - code can/should/will be refactored. this is part of my plan

**Comment by AndrewSerra** [comment]
> thanks for the clear explanation. it save me a lot of time.
> 
> at this point i want just to not have an import of our examples and schemas inside of try/catch

Sure I will remove them now. Sorry for the late response I was taken to the hospital and did not have access to my phone or laptop. All good now handling the imports now and will open a pull request.

**Comment by atherdon** [comment]
not a problem at all - hope everything is going well with you - work can
wait but health are most important thing

>
